import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
  pageContainer: {
    display: 'flex',
    height: `calc(100vh - 126px)`,
    backgroundColor: '#f0f2f5',
  },
  sidebar: {
    width: '300px',
    borderRight: '1px solid rgba(0,0,0,0.1)',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  chatList: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px',
  },
  chatItem: {
    padding: '10px 15px',
    borderRadius: '8px',
    cursor: 'pointer',
    marginBottom: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    '&:hover': {
      backgroundColor: 'rgba(0,0,0,0.05)',
    },
  },
  chatItemActive: {
    backgroundColor: token.colorPrimaryBg,
    '&:hover': {
      backgroundColor: token.colorPrimaryBg,
    },
  },
  newChatButton: {
    margin: '12px',
  },
  chatContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
  },
  messageList: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px',
    '&::-webkit-scrollbar': {
      width: '6px',
      height: '6px',
    },
    '&::-webkit-scrollbar-thumb': {
      background: 'rgba(0, 0, 0, 0.1)',
      borderRadius: '3px',
      '&:hover': {
        background: 'rgba(0, 0, 0, 0.2)',
      },
    },
    '&::-webkit-scrollbar-track': {
      background: 'transparent',
    },
  },
  messageGroup: {
    padding: '16px 0',
    '&:first-child': {
      marginTop: 'auto',
    },
  },
  messageContent: {
    maxWidth: '800px',
    margin: '0 auto',
    padding: '0 24px',
  },
  messageItem: {
    display: 'flex',
    gap: '20px',
    alignItems: 'flex-start',
    maxWidth: '100%',
  },
  userMessageItem: {
    flexDirection: 'row-reverse',
    gap: '0',
  },
  avatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: token.colorPrimary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontSize: '16px',
    flexShrink: 0,
    marginRight: '12px',
  },
  messageText: {
    flex: '0 1 auto',
    fontSize: '16px',
    lineHeight: 1.6,
    maxWidth: '60%',
  },
  userMessageText: {
    backgroundColor: token.colorPrimary,
    color: '#fff',
    padding: '8px',
    borderRadius: '12px',
    marginLeft: 'auto',
    wordWrap: 'break-word',
    whiteSpace: 'pre-wrap',
    '& p': {
      margin: 0,
    },
  },
  assistantMessageText: {
    backgroundColor: '#f4f6f8',
    padding: '8px',
    borderRadius: '12px',
    wordWrap: 'break-word',
    whiteSpace: 'pre-wrap',
    '& p': {
      margin: 0,
    },
  },
  reasoningText: {
    color: token.colorTextSecondary,
    fontSize: '14px',
    fontStyle: 'italic',
    padding: '8px 12px',
    backgroundColor: 'rgba(247,247,248,0.8)',
    borderRadius: '6px',
    marginBottom: '12px',
    borderLeft: `3px solid ${token.colorPrimary}`,
    maxWidth: '100%',
    '& p': {
      margin: 0,
    },
  },
  inputArea: {
    borderTop: '1px solid rgba(0,0,0,0.1)',
    padding: '24px',
    position: 'relative',
    backgroundColor: '#fff',
  },
  inputContainer: {
    maxWidth: '600px',
    margin: '0 auto',
    position: 'relative',
  },
  textArea: {
    padding: '12px 16px',
    paddingRight: '48px',
    resize: 'none',
    borderRadius: '12px',
    boxShadow: '0 0 0 1px rgba(0,0,0,0.1)',
    fontSize: '16px',
    lineHeight: '24px',
    '&:focus': {
      boxShadow: `0 0 0 1px ${token.colorPrimary}`,
    },
  },
  sendButton: {
    position: 'absolute',
    right: '12px',
    bottom: '12px',
    width: '32px',
    height: '32px',
    padding: 0,
    borderRadius: '8px',
  },
  stopButtonContainer: {
    position: 'absolute',
    bottom: '100%',
    left: '50%',
    transform: 'translateX(-50%)',
    marginBottom: '30px',
    zIndex: 100,
  },
  stopButton: {
    borderRadius: '24px',
    padding: '6px 24px',
    height: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    border: '1px solid rgba(0, 0, 0, 0.1)',
    color: token.colorTextSecondary,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: 'rgba(0, 0, 0, 0.1)',
      borderColor: 'rgba(0, 0, 0, 0.15)',
      color: token.colorText,
    },
  },
  stopIcon: {
    fontSize: '16px',
  },
  logoContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '18px',
    marginRight: '10px',
    width: '50px',
    height: '50px',
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: '8px',
  },
  welcomeMessage: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    fontSize: '24px',
    fontWeight: 'bold',
    color: token.colorTextSecondary,
  },
}));
