import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
  pageContainer: {
    display: 'flex',
    height: `calc(100vh - 126px)`,
    backgroundColor: '#f0f2f5',
  },
  sidebar: {
    width: '300px',
    borderRight: '1px solid rgba(0,0,0,0.1)',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#fff',
  },
  chatList: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px',
  },
  chatItem: {
    padding: '10px 15px',
    borderRadius: '8px',
    cursor: 'pointer',
    marginBottom: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    '&:hover': {
      backgroundColor: 'rgba(0,0,0,0.05)',
    },
  },
  chatItemActive: {
    backgroundColor: token.colorPrimaryBg,
    '&:hover': {
      backgroundColor: token.colorPrimaryBg,
    },
  },
  newChatButton: {
    margin: '12px',
    background: 'linear-gradient(135deg, #7C4DFF 0%, #5C6BC0 100%)',
  },
  chatContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
  },
  messageList: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px',
    '&::-webkit-scrollbar': {
      width: '6px',
      height: '6px',
    },
    '&::-webkit-scrollbar-thumb': {
      background: 'rgba(0, 0, 0, 0.1)',
      borderRadius: '3px',
      '&:hover': {
        background: 'rgba(0, 0, 0, 0.2)',
      },
    },
    '&::-webkit-scrollbar-track': {
      background: 'transparent',
    },
  },
  messageGroup: {
    padding: '12px 0',
    '&:first-child': {
      marginTop: 'auto',
    },
  },
  messageContent: {
    maxWidth: '850px',
    margin: '0 auto',
    padding: '0 24px',
  },
  messageItem: {
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
    maxWidth: '100%',
  },
  userMessageItem: {
    flexDirection: 'row-reverse',
  },
  avatar: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    backgroundColor: token.colorPrimary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontSize: '16px',
    flexShrink: 0,
  },
  messageText: {
    flex: '0 1 auto',
    fontSize: '15px',
    lineHeight: 1.6,
    maxWidth: '85%',
  },
  userMessageText: {
    background: 'linear-gradient(135deg, #7C4DFF 0%, #5C6BC0 100%)',
    color: '#fff',
    padding: '8px',
    borderRadius: '16px 16px 2px 16px',
    marginLeft: 'auto',
    wordWrap: 'break-word',
    whiteSpace: 'pre-wrap',
    boxShadow: '0 2px 12px rgba(124, 77, 255, 0.15)',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(255, 255, 255, 0.12)',
    '& p': {
      margin: 0,
    },
    '& code': {
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      padding: '2px 6px',
      borderRadius: '4px',
      border: '1px solid rgba(255, 255, 255, 0.2)',
    },
    transition: 'all 0.3s ease',
    '&:hover': {
      boxShadow: '0 4px 16px rgba(124, 77, 255, 0.2)',
      transform: 'translateY(-1px)',
    },
  },
  assistantMessageText: {
    backgroundColor: '#fff',
    padding: '12px 16px',
    borderRadius: '16px 16px 16px 2px',
    wordWrap: 'break-word',
    whiteSpace: 'pre-wrap',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.06)',
    border: '1px solid rgba(0, 0, 0, 0.08)',
    '& p': {
      margin: 0,
    },
    '& code': {
      backgroundColor: '#f6f8fa',
      padding: '2px 6px',
      borderRadius: '4px',
    },
  },
  reasoningText: {
    color: token.colorTextSecondary,
    fontSize: '14px',
    padding: '12px 16px',
    backgroundColor: '#fff',
    borderRadius: '12px',
    marginBottom: '8px',
    border: '1px solid rgba(0, 0, 0, 0.08)',
    position: 'relative',
    '&::before': {
      content: '""',
      position: 'absolute',
      left: '-1px',
      top: '0',
      bottom: '0',
      width: '3px',
      background: 'linear-gradient(180deg, #1677ff 0%, rgba(22, 119, 255, 0.3) 100%)',
      borderRadius: '3px',
    },
    '& p': {
      margin: 0,
    },
  },
  inputArea: {
    borderTop: '1px solid rgba(0, 0, 0, 0.06)',
    padding: '20px 24px',
    position: 'relative',
    backgroundColor: '#fff',
  },
  inputContainer: {
    maxWidth: '850px',
    margin: '0 auto',
    position: 'relative',
  },
  textArea: {
    padding: '12px 16px',
    paddingRight: '48px',
    resize: 'none',
    borderRadius: '12px',
    boxShadow: '0 0 0 1px rgba(0, 0, 0, 0.1)',
    fontSize: '15px',
    lineHeight: '24px',
    transition: 'all 0.3s ease',
    '&:focus': {
      boxShadow: `0 0 0 2px ${token.colorPrimary}20`,
      borderColor: token.colorPrimary,
    },
  },
  sendButton: {
    position: 'absolute',
    right: '12px',
    bottom: '12px',
    width: '32px',
    height: '32px',
    padding: 0,
    borderRadius: '8px',
  },
  stopButtonContainer: {
    position: 'absolute',
    bottom: '100%',
    left: '50%',
    transform: 'translateX(-50%)',
    marginBottom: '30px',
    zIndex: 100,
  },
  stopButton: {
    borderRadius: '24px',
    padding: '6px 24px',
    height: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    border: '1px solid rgba(0, 0, 0, 0.1)',
    color: token.colorTextSecondary,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: 'rgba(0, 0, 0, 0.1)',
      borderColor: 'rgba(0, 0, 0, 0.15)',
      color: token.colorText,
    },
  },
  stopIcon: {
    fontSize: '16px',
  },
  logoContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '18px',
    marginRight: '10px',
    width: '50px',
    height: '50px',
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: '8px',
  },
  welcomeMessage: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    fontSize: '24px',
    fontWeight: 'bold',
    color: token.colorTextSecondary,
  },
}));
