# 工作流的名称
name: Deploy React App

# 触发工作流的条件
on:
  push:
    branches:
      - release/181 # 当代码推送到main分支时触发
  pull_request:
    branches:
      - release/181 # 当有针对main分支的PR时触发

# 定义要执行的任务
jobs:
  # 任务名称为build-and-deploy
  build-and-deploy:
    # 指定运行环境为最新版本的Ubuntu
    runs-on: ubuntu-latest

    # 定义任务的步骤
    steps:
      # 第1步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v2 # 使用官方的checkout action

      # 第2步：设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v2 # 使用官方的setup-node action
        with:
          node-version: '16' # 指定Node.js版本

      # 第3步：安装项目依赖
      - name: Install dependencies
        run: npm install # 执行npm install命令

      # 第4步：构建项目
      - name: Build project
        run: npm run build:prod # 执行构建命令

      # 第5步：列出构建目录
      - name: List build directory
        run: ls -la dist/

      # 第6步：部署到服务器
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          debug: true # 添加调试输出
          host: ${{ secrets.SERVER_HOST_181 }}
          username: ${{ secrets.SERVER_USERNAME_181 }}
          key: ${{ secrets.SERVER_SSH_KEY_181 }}
          source: 'dist/*'
          target: '/var/www/shortlink/dist'
          strip_components: 1

      # 添加第7步：重启 nginx
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_181 }}
          username: ${{ secrets.SERVER_USERNAME_181 }}
          key: ${{ secrets.SERVER_SSH_KEY_181 }}
          script: |
            sudo systemctl restart nginx
            echo "Nginx has been restarted"
